## Final project

{{< include ../_links.qmd >}}

### General info

Overall your work on the final projectl project counts for 50% of the
final grade

Using your own dataset (or one provided by me):

1.  develop a question of interest
2.  choose the statistical analysis appropriate to answer the question
3.  **give a short presentation during the class about your analysis plan**
4.  analyse the data using R
5.  **Prepare a short report using Quarto** including code and outputs for:
    -   exploratory plots
    -   analysis
    -   model assumptions checks
    -   result illustrations (plots)
6.  Prepare a **15min presentation** as a statisticial report
7.  submit your work via Brightspace before the deadline
8. **30min oral exam** (presentation and questions)

Your submission on Brightspace needs to include:

1.  slides for your final presentation (in your preferred format)
2.  rendered html of your short report
3.  .qmd file (used to generate the html)
4.  data file(s) used
5.  extra files needed to reproduce the document
    -   .bib files
    -   .csl files
    -   ...

Missing files needed to render the final short report would incur a 10% penalty on the report grade

### Rubric

#### Analysis plan presentation (10%)

5-10 minutes presentation of your analysis plan including:

-   research question/hypothesis
-   data structure
-   potential analysis


#### Final report (10%)

Document contains all analysis done, is reproducible, clear, well organized and commented (5%)

#### Final oral examination (30%)

Oral examination will be one-on-one during the exam period. It will last 30 minutes including a 12-15 minutes presentation of your work intertwined with questions from the examiner. 

##### Presentation structure
###### Introduction

-   Background of the general ‘big picture’ and specific problem,
-   study system
-   specific hypotheses to be tested
-   predictions

###### Methods

-   Brief outline of data collection
-   clear explanation of statistical methods used to address the
    hypotheses/predictions outlined in the introduction, including key
    assumptions.

###### Results

Text and visualizations clearly summarizing your results, using parallel
structure to methods. Should include :

-   clear graphics representing the data and the model outputs,
-   tables reporting statistics
-   text describing results
-   evaluation of model assumption and model fit

##### Discussion

-   Summary of major results
-   conclusions/implications
-   Limitations of analysis (power, complexity of model, data structure,
    ...)
-   future directions